# Setup RoleBinding between Role and ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RELEASE-NAME-clickhouse-operator
  namespace: NAMESPACE
  labels:
    helm.sh/chart: clickhouse-24.1.18
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: "24.1.2"
    app.kubernetes.io/managed-by: Helm
    clickhouse.altinity.com/chop: 0.21.2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: RELEASE-NAME-clickhouse-operator
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-clickhouse-operator
  namespace: NAMESPACE
