apiVersion: v1
kind: Namespace
metadata:
  name: signoz
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/version: "v0.93.0"
    app.kubernetes.io/managed-by: kustomize
