apiVersion: v1
kind: Service
metadata:
  name: signoz-otel-collector
  namespace: signoz
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/version: "v0.93.0"
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: otlp
      port: 4317
      targetPort: otlp
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
    - name: jaeger-thrift
      port: 14268
      targetPort: jaeger-thrift
      protocol: TCP
    - name: jaeger-grpc
      port: 14250
      targetPort: jaeger-grpc
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: metrics
      protocol: TCP
    - name: logsheroku
      port: 8081
      targetPort: logsheroku
      protocol: TCP
    - name: logsjson
      port: 8082
      targetPort: logsjson
      protocol: TCP
  selector:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: otel-collector
