apiVersion: v1
kind: Service
metadata:
  name: signoz
  namespace: signoz
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: signoz
    app.kubernetes.io/version: "v0.93.0"
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: http-internal
      port: 8085
      protocol: TCP
      targetPort: http-internal
    - name: opamp-internal
      port: 4320
      protocol: TCP
      targetPort: opamp-internal
  selector:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: signoz
