{{- if (include "postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
type: Opaque
data:
  {{ include "postgresql.secretPasswordKey" . }}: {{ .Values.externalPostgresql.password | b64enc | quote }}
{{- end }}
