apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
{{- with .Values.frontend.service }}
{{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      {{- include "signoz.service.ifClusterIP" .type | nindent 6 }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
