{{- if and .Values.postgres.enabled .Values.postgres.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres.serviceAccountName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.postgres.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "postgres.imagePullSecrets" . }}
{{- end -}}
