{{- if .Values.otelAgent.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelAgent.fullname" . }}
  namespace: {{ include "k8s-infra.namespace" . }}
  labels:
    {{- include "otelAgent.labels" . | nindent 4 }}
{{- with .Values.otelAgent }}
  {{- if .service.annotations }}
  annotations:
    {{- toYaml .service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .service.type }}
  ports:
    {{- include "otel.portsConfig" . | nindent 4 }}
  selector:
    {{- include "otelAgent.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
