{{- if and .Values.otelDeployment.clusterRole.create .Values.otelDeployment.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otelDeployment.clusterRoleName" . }}
  namespace: {{ include "k8s-infra.namespace" . }}
  {{- with .Values.otelDeployment.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.otelDeployment.clusterRole.rules | nindent 2 }}
{{- end }}
