apiVersion: v2
name: alertmanager
description: The Alertmanager handles alerts for SigNoz.
type: application
version: 0.5.1
appVersion: "0.5.0"
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
maintainers:
  - name: signoz
    email: hello@signoz.io
