apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "schemaMigrator.fullname" . }}-migration
  labels:
    {{- include "schemaMigrator.selectorLabels" . | nindent 4 }}
  {{- if .Values.schemaMigrator.annotations }}
  annotations:
    {{- toYaml .Values.schemaMigrator.annotations | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "schemaMigrator.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- if .Values.schemaMigrator.initContainers.init.enabled }}
        - name: {{ include "schemaMigrator.fullname" . }}-init
          # todo: use schema migrator variables here
          image: {{ include "schemaMigrator.initContainers.init.image" . }}
          imagePullPolicy: {{ .Values.schemaMigrator.initContainers.init.image.pullPolicy }}
          env:
            {{- include "snippet.clickhouse-credentials" . | nindent 12 }}
          {{- with .Values.schemaMigrator.initContainers.init.command }}
          command:
            - sh
            - -c
            - until wget --user "$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)" --spider -q {{ include "clickhouse.httpUrl" $ }}{{ .endpoint }}; do echo -e "{{ .waitMessage }}"; sleep {{ .delay }}; done; echo -e "{{ .doneMessage }}";
          {{- end }}
          resources:
            {{- toYaml .Values.schemaMigrator.initContainers.init.resources | nindent 12 }}
        {{- end }}
        # ClickHouse sanity check
        {{- if and .Values.clickhouse.enabled .Values.schemaMigrator.initContainers.chSanity.enabled }}
        - name: {{ include "schemaMigrator.fullname" . }}-ch-sanity
          image: {{ include "schemaMigrator.initContainers.chSanity.image" . }}
          imagePullPolicy: {{ .Values.schemaMigrator.initContainers.chSanity.image.pullPolicy }}
          env:
            {{- include "snippet.clickhouse-credentials" . | nindent 12 }}
            - name: CLICKHOUSE_VERSION
              value: {{ trimSuffix "-alpine" .Values.clickhouse.image.tag }}
            - name: CLICKHOUSE_SHARDS
              value: {{ default 1 .Values.clickhouse.layout.shardCount | quote }}
          {{- with .Values.schemaMigrator.initContainers.chSanity.command }}
          command: {{ . | toYaml | nindent 12 }} 
          {{- end }}
          resources:
            {{- toYaml .Values.schemaMigrator.initContainers.chSanity.resources | nindent 12 }}
        {{- end }}
      containers:
        - name: schema-migrator
          image: {{ include "schemaMigrator.image" . }}
          imagePullPolicy: {{ .Values.schemaMigrator.image.pullPolicy }}
          env:
            {{- include "snippet.clickhouse-credentials" . | nindent 12 }}
          args:
            - "--dsn"
            - "tcp://{{ include "schemamigrator.url" . }}?username=$(CLICKHOUSE_USER)&password=$(CLICKHOUSE_PASSWORD)"
            {{- range .Values.schemaMigrator.args }}
            - {{ . | quote }}
            {{- end }}
      restartPolicy: OnFailure