{{- if .Values.telemetryStoreMigrator.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "telemetryStoreMigrator.roleBindingName" . }}
  namespace: {{ include "signoz.namespace" . }}
  {{- with .Values.telemetryStoreMigrator.role.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "telemetryStoreMigrator.roleName" . }}
subjects:
  - name: {{ include "telemetryStoreMigrator.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ include "signoz.namespace" . }}
{{- end }}
