{{- if .Values.telemetryStoreMigrator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetryStoreMigrator.serviceAccountName" . }}
  labels:
    {{- include "telemetryStoreMigrator.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.telemetryStoreMigrator.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.telemetryStoreMigrator.upgradeHelmHooks }}
    argocd.argoproj.io/sync-options: Force=true,Replace=true
    {{- if .Release.IsUpgrade }}
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    {{- end }}
    {{- end }}
{{- include "signoz.imagePullSecrets" . }}
{{- end -}}
