apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-clickhouse-custom-functions
  namespace: NAMESPACE
  labels:
    helm.sh/chart: clickhouse-24.1.18
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/version: "24.1.2"
    app.kubernetes.io/managed-by: Helm
data:
  custom-functions.xml: |
    <functions>
        <function>
            <type>executable</type>
            <name>histogramQuantile</name>
            <return_type>Float64</return_type>
            <argument>
                <type>Array(Float64)</type>
                <name>buckets</name>
            </argument>
            <argument>
                <type>Array(Float64)</type>
                <name>counts</name>
            </argument>
            <argument>
                <type>Float64</type>
                <name>quantile</name>
            </argument>
            <format>CSV</format>
            <command>./histogramQuantile</command>
        </function>
    </functions>
