
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-clickhouse
  namespace: NAMESPACE
  labels:
    helm.sh/chart: clickhouse-24.1.18
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/version: "24.1.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
