# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clickhouseOperator.fullname" . }}-{{ include "clickhouse.namespace" . }}
  namespace: {{ include "clickhouse.namespace" . }}
  labels:
    {{- include "clickhouseOperator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clickhouseOperator.fullname" . }}-{{ include "clickhouse.namespace" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.clickhouseOperator.serviceAccount.create }}
  name: {{ include "clickhouseOperator.fullname" . }}
  {{- else }}
  name: {{ .Values.clickhouseOperator.serviceAccount.name }}
  {{- end }}
  namespace: {{ include "clickhouse.namespace" . }}
