# Setup RoleBinding between Role and ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "clickhouseOperator.fullname" . }}
  namespace: {{ include "clickhouse.namespace" . }}
  labels:
    {{- include "clickhouseOperator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "clickhouseOperator.fullname" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.clickhouseOperator.serviceAccount.create }}
  name: {{ include "clickhouseOperator.fullname" . }}
  {{- else }}
  name: {{ .Values.clickhouseOperator.serviceAccount.name }}
  {{- end }}
  namespace: {{ include "clickhouse.namespace" . }}
