{{- if .Values.clickhouseOperator.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clickhouseOperator.secret.name | default (include "clickhouseOperator.fullname" .) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels: {{ include "clickhouseOperator.labels" . | nindent 4 }}
type: Opaque
{{- if hasKey .Values.clickhouseOperator.secret "immutable" }}
immutable: {{ .Values.clickhouseOperator.secret.immutable }}
{{- end }}
stringData:
  {{- $ns := (default .Release.Namespace .Values.namespace) }}
  {{- $secName := (default (include "clickhouseOperator.fullname" .) .Values.clickhouseOperator.secret.name) }}
  {{- $existing := (lookup "v1" "Secret" $ns $secName) }}
  {{- $passwordKey := (default "password" .Values.clickhouseOperator.secret.passwordKey) }}
  {{- $existingPw := "" }}
  {{- if and $existing $existing.data }}
    {{- if hasKey $existing.data $passwordKey }}
      {{- $existingPw = b64dec (index $existing.data $passwordKey) }}
    {{- end }}
  {{- end }}
  {{- $username := required ".Values.clickhouseOperator.secret.username is required when secret.create is true" .Values.clickhouseOperator.secret.username }}
  {{- $password := .Values.clickhouseOperator.secret.password | default $existingPw | default (randAlphaNum 24) }}
  {{- $uKey := (default "username" .Values.clickhouseOperator.secret.usernameKey) }}
  {{- if not (regexMatch "^[A-Za-z0-9._-]+$" $uKey) }}
  {{- fail "Invalid .Values.clickhouseOperator.secret.usernameKey: must match ^[A-Za-z0-9._-]+$" }}
  {{- end }}
  {{- if or (eq $uKey ".") (eq $uKey "..") }}
  {{- fail "Invalid .Values.clickhouseOperator.secret.usernameKey: cannot be '.' or '..'" }}
  {{- end }}
  {{- $pKey := (default "password" .Values.clickhouseOperator.secret.passwordKey) }}
  {{- if not (regexMatch "^[A-Za-z0-9._-]+$" $pKey) }}
  {{- fail "Invalid .Values.clickhouseOperator.secret.passwordKey: must match ^[A-Za-z0-9._-]+$" }}
  {{- end }}
  {{- if or (eq $pKey ".") (eq $pKey "..") }}
  {{- fail "Invalid .Values.clickhouseOperator.secret.passwordKey: cannot be '.' or '..'" }}
  {{- end }}
  {{- if eq $uKey $pKey }}
  {{- fail "usernameKey and passwordKey must be different" }}
  {{- end }}
  {{ $uKey }}: {{ $username | quote }}
  {{ $pKey }}: {{ $password | quote }}
{{- end -}}
