{{- if .Values.clickhouseOperator.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clickhouseOperator.secret.name | default (include "clickhouseOperator.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "clickhouseOperator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.clickhouseOperator.secret.usernameKey | default "username" }}: {{ if not .Values.clickhouseOperator.secret.username }}{{ fail "You must set .Values.clickhouseOperator.secret.username when create: true" }}{{ else }}{{ .Values.clickhouseOperator.secret.username | b64enc }}{{ end }}
  {{ .Values.clickhouseOperator.secret.passwordKey | default "password" }}: {{ if not .Values.clickhouseOperator.secret.password }}{{ fail "You must set .Values.clickhouseOperator.secret.password when create: true" }}{{ else }}{{ .Values.clickhouseOperator.secret.password | b64enc }}{{ end }}
{{- end -}}
