{{- if (default false (default dict .Values.clickhouseOperator.secret).create) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clickhouseOperator.secret.name | default (include "clickhouseOperator.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "clickhouseOperator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.clickhouseOperator.secret.username }}
  username: {{ .Values.clickhouseOperator.secret.username | b64enc }}
  {{- end }}
  {{- if .Values.clickhouseOperator.secret.password }}
  password: {{ .Values.clickhouseOperator.secret.password | b64enc }}
  {{- end }}
{{- end -}}
