{{- if .Values.clickhouseOperator.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clickhouseOperator.secret.name | default (include "clickhouseOperator.fullname" .) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels: {{ include "clickhouseOperator.labels" . | nindent 4 }}
type: Opaque
{{- if hasKey .Values.clickhouseOperator.secret "immutable" }}
immutable: {{ .Values.clickhouseOperator.secret.immutable }}
{{- end }}
stringData:
  {{- $uKey := (default "username" .Values.clickhouseOperator.secret.usernameKey) }}
  {{- if not (regexMatch "^[A-Za-z0-9._-]+$" $uKey) }}
  {{- fail "Invalid .Values.clickhouseOperator.secret.usernameKey: must match ^[A-Za-z0-9._-]+$" }}
  {{- end }}
  {{- $pKey := (default "password" .Values.clickhouseOperator.secret.passwordKey) }}
  {{- if not (regexMatch "^[A-Za-z0-9._-]+$" $pKey) }}
  {{- fail "Invalid .Values.clickhouseOperator.secret.passwordKey: must match ^[A-Za-z0-9._-]+$" }}
  {{- end }}
  {{ $uKey }}: {{ required ".Values.clickhouseOperator.secret.username is required when secret.create is true" .Values.clickhouseOperator.secret.username }}
  {{ $pKey }}: {{ required ".Values.clickhouseOperator.secret.password is required when secret.create is true" .Values.clickhouseOperator.secret.password }}
{{- end -}}
