{{- if .Values.clickhouseOperator.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouseOperator.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels: {{ include "clickhouseOperator.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.clickhouseOperator.secret.username | b64enc }}
  password: {{ .Values.clickhouseOperator.secret.password | b64enc }}
{{- end -}}
