{{- if .Values.clickhouseOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouseOperator.serviceAccountName" . }}
  namespace: {{ include "clickhouse.namespace" . }}
  labels:
    {{- include "clickhouseOperator.labels" . | nindent 4 }}
{{- with .Values.clickhouseOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- include "clickhouseOperator.imagePullSecrets" . }}
{{- end }}
