# Template Parameters:
#
# NAMESPACE={{ include "clickhouse.namespace" . }}
# COMMENT=
#
# Setup ClusterIP Service to provide monitoring metrics for Prometheus
# Service would be created in kubectl-specified namespace
# In order to get access outside of k8s it should be exposed as:
# kubectl --namespace prometheus port-forward service/prometheus 9090
# and point browser to localhost:9090
kind: Service
apiVersion: v1
metadata:
  name: {{ include "clickhouseOperator.fullname" . }}-metrics
  namespace: {{ include "clickhouse.namespace" . }}
  labels:
    {{- include "clickhouseOperator.labels" . | nindent 4 }}
{{- with .Values.clickhouseOperator.metricsExporter.service }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      name: {{ include "clickhouseOperator.fullname" $ }}-metrics
  selector:
    {{- include "clickhouseOperator.selectorLabels" $ | nindent 4 }}
{{- end }}
