# Template Parameters:
#
# COMMENT=
# NAMESPACE=platform
# NAME=clickhouse-instance
#
# Setup ServiceAccount

{{- if .Values.coldStorage.role.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-instance
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  {{- with .Values.coldStorage.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
