apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelCollectorMetrics.fullname" . }}
  labels:
    {{- include "otelCollectorMetrics.labels" . | nindent 4 }}
{{- with .Values.otelCollectorMetrics }}
{{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .service.type }}
  ports:
    {{- include "otelCollector.portsConfig" . | indent 4 -}}
{{- end }}
  selector:
    {{- include "otelCollectorMetrics.selectorLabels" . | nindent 4 }}
