apiVersion: v1
kind: Service
metadata:
  name: otel-collector-metrics
  labels:
    app: opentelemetry
    component: otel-collector-metrics
spec:
  ports:
  - name: otlp # Default endpoint for OpenTelemetry receiver.
    port: 55680
    protocol: TCP
    targetPort: 55680
  - name: otlp-http-legacy # Default endpoint for OpenTelemetry receiver.
    port: 55681
    protocol: TCP
    targetPort: 55681
  - name: otlp-grpc # Default endpoint for OpenTelemetry receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: jaeger-grpc # Default endpoing for Jaeger gRPC receiver
    port: 14250
  - name: jaeger-thrift-http # Default endpoint for Jaeger HTTP receiver.
    port: 14268
  - name: zipkin # Default endpoint for Zipkin receiver.
    port: 9411
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: otel-collector-metrics