{{- if .Values.otelCollectorMetrics.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otelCollectorMetrics.serviceAccountName" . }}
  labels:
    {{- include "otelCollectorMetrics.labels" . | nindent 4 }}
  {{- with .Values.otelCollectorMetrics.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "signoz.imagePullSecrets" . }}
{{- end -}}
