{{- if .Values.externalSecrets.create }}

{{- $genericConfig := dict -}}
{{- $_ := set $genericConfig "fullName" (include "signoz-otel-gateway.fullname" .) -}}
{{- $_ := set $genericConfig "namespace" .Release.Namespace -}}
{{- $_ := set $genericConfig "labels" (include "signoz-otel-gateway.labels" .) -}}
{{- $_ := set $genericConfig "secretStoreKind" .Values.externalSecrets.secretStoreRef.kind -}}
{{- $_ := set $genericConfig "secretStoreName" .Values.externalSecrets.secretStoreRef.name -}}

{{- range $key, $value := .Values.externalSecrets.secrets }}
  {{- $config := mustDeepCopy $genericConfig -}}
  {{- $_ := set $config "name" $key -}}
  {{- $_ := set $config "dataFrom" $value.dataFrom -}}
  {{- include "signoz-otel-gateway.secret" $config -}}
{{- end }}

{{- end }}

{{- define "signoz-otel-gateway.secret" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .fullName }}-{{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- .labels | nindent 4 }}
spec:
  secretStoreRef:
    kind: {{ required "externalSecrets.secretStoreRef.kind is required" .secretStoreKind }}
    name: {{ required "externalSecrets.secretStoreRef.name is required" .secretStoreName  }}
  target:
    name: {{ .fullName }}-{{ .name }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .dataFrom | required "externalSecrets.secrets.dataFrom is required" }}
{{- end }}
