apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  name: {{ include "signoz-otel-gateway.fullname" . }}
  labels:
    {{- include "signoz-otel-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "signoz-otel-gateway.ports" . | indent 4 }}
  selector:
    {{- include "signoz-otel-gateway.selectorLabels" . | nindent 4 }}
