{{- if .Values.installCustomStorageClass.enabled -}}

{{- if (eq (.Values.cloud | toString) "gcp" ) -}}
#
# GCP resizable storage class
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-resizable
provisioner: kubernetes.io/gce-pd
parameters:
  type: {{ .Values.installCustomStorageClass.storageType }}
  fstype: ext4
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true

{{- else if (eq (.Values.cloud | toString) "aws") -}}
#
# AWS resizable storage class
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-resizable
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ .Values.installCustomStorageClass.storageType }}
reclaimPolicy: Retain
allowVolumeExpansion: true
{{- end -}}
{{- end }}
