apiVersion: v2
appVersion: v2.8.0
description: Helm chart to deploy Redpanda Console.
icon: https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg
kubeVersion: '>= 1.25.0-0'
maintainers:
- name: SigNoz
  email: hello@signoz.io
  url: https://signoz.io
name: console
sources:
- https://github.com/redpanda-data/helm-charts
type: application
version: 0.7.31
