{{- if and (not .Values.presets.selfTelemetry.apiKeyExistingSecretName) .Values.presets.selfTelemetry.signozApiKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "k8s-infra.fullname" . }}-self-telemetry-apikey-secret
  namespace: {{ include "k8s-infra.namespace" . }}
  labels:
    {{- include "k8s-infra.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  signoz-apikey: {{ .Values.presets.selfTelemetry.signozApiKey | b64enc | quote }}
{{- end }}
