{{- if and (not .Values.apiKeyExistingSecretName) .Values.signozApiKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "k8s-infra.fullname" . }}-apikey-secret
  labels:
    {{- include "k8s-infra.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  signoz-apikey: {{ .Values.signozApiKey | b64enc | quote }}
{{- end }}
