apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signoz-minimal

resources:
  - ../../base

# Minimal-specific patches
patches:
  - target:
      kind: StatefulSet
      name: signoz
      namespace: signoz-minimal
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

  - target:
      kind: Deployment
      name: signoz-otel-collector
      namespace: signoz-minimal
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

# Minimal-specific labels
labels:
  - pairs:
      environment: minimal
      tier: minimal

# Minimal-specific images
images:
  - name: docker.io/signoz/signoz
    newTag: v0.93.0
