{{- if .Values.schemaMigrator.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "schemaMigrator.roleBindingName" . }}-async
  namespace: {{ include "signoz.namespace" . }}
  annotations:
    {{- with .Values.schemaMigrator.role.roleBinding.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Release.IsUpgrade .Values.schemaMigrator.upgradeHelmHooks }}
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "schemaMigrator.roleName" . }}-async
subjects:
  - name: {{ include "schemaMigrator.serviceAccountName" . }}-async
    kind: ServiceAccount
    namespace: {{ include "signoz.namespace" . }}
{{- end }}
