{{- if .Values.logs.system.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-logs-system-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.logs.system.config | nindent 4 }}
{{- end }}