apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-scripts
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  wait-until-ready.sh: |
    #!/bin/bash
    
    # Delay between attempts in seconds
    DELAY=10
    # Default host and port
    HOST="localhost"
    PORT="8123"
    
    echo "Waiting for Clickhouse to become ready..."
    
    while true; do
        response=$(wget --spider -S "http://${HOST}:${PORT}/ping" 2>&1)
        exit_code=$?
        
        if [ $exit_code -eq 0 ]; then
            echo "Clickhouse is ready!"
            exit 0
        else
            echo "Clickhouse is not ready yet. Retrying in ${DELAY} seconds..."
            sleep $DELAY
        fi
    done
