{{- if .Values.clickhouseInstance.enabled }}
{{- if or .Values.clickhouseInstance.coldStorage.role.enabled .Values.clickhouseInstance.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouse.serviceAccountName" . }}
  namespace: {{ include "clickhouse.namespace" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  {{- include "clickhouse.serviceAccountAnnotations" . | nindent 2 }}
{{- include "clickhouse.imagePullSecrets" . }}
{{- end }}
{{- end }}
