apiVersion: v2
name: clickhouse
description: A Helm chart for ClickHouse
type: application
version: 25.12.5
appVersion: "25.12.5"
icon: https://github.com/ClickHouse/clickhouse-docs/raw/84f38d893eb7e561c7296279d7953b6a508ec413/static/img/clickhouse-logo.svg
sources:
  - https://github.com/SigNoz/charts
  - https://github.com/ClickHouse/ClickHouse
maintainers:
  - name: SigNoz
    email: hello@signoz.io
    url: https://signoz.io