apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otelCollector.fullname" . }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |-
    {{- toYaml .Values.otelCollector.config | nindent 4 }}
  otel-collector-opamp-config.yaml: |-
    server_endpoint: "ws://{{ include "queryService.fullname" . }}:4320/v1/opamp"
