{{- if and .Values.otelCollector.autoscaling.keda.enabled .Values.otelCollector.autoscaling.keda.bearer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otelCollector.fullname" . }}-keda-secret
data:
  bearerToken: {{ .Values.otelCollector.autoscaling.keda.bearer.token | b64enc }}
  {{- with .Values.otelCollector.autoscaling.keda.bearer.customCA }}
  ca: {{ . | b64enc }}
  {{- end }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.otelCollector.autoscaling.keda.bearer.triggerAuth }}
spec:
  secretTargetRef:
    - parameter: bearerToken
      name: {{ include "otelCollector.fullname" . }}-keda-secret
      key: bearerToken
    {{- if .Values.otelCollector.autoscaling.keda.bearer.customCA }}
    - parameter: ca
      name: {{ include "otelCollector.fullname" . }}-keda-secret
      key: ca
    {{- end }}
{{- end }}
