annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.8.1
dependencies:
- name: common
  repository: "file://charts/common"
  tags:
  - bitnami-common
  version: 2.4.0
description: Apache ZooKeeper provides a reliable, centralized register of configuration
  data and services for distributed applications.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/zookeeper/img/zookeeper-stack-220x234.png
keywords:
- zookeeper
maintainers:
- name: SigNoz
  email: hello@signoz.io
  url: https://signoz.io
name: zookeeper
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/zookeeper
version: 11.4.2
