{{- $files := dig "configs" "confdFiles" nil .Values.clickhouseOperator -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouseOperator.fullname" . }}-etc-confd-files
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "clickhouseOperator.labels" . | nindent 4 }}
data: {{- if $files }}
{{- range $name, $contents := $files }}
  {{ $name }}: {{ tpl ($contents | toString) $ | toYaml | nindent 4 }}
{{- end }}
{{- else }} {{ tpl (toYaml $files) . | nindent 2 }}
{{- end }}
