apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouseOperator.fullname" . }}-etc-confd-files
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "clickhouseOperator.labels" . | nindent 4 }}
data: {{ tpl (toYaml .Values.clickhouseOperator.configs.confdFiles) . | nindent 2 }}
