apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouseOperator.fullname" . }}-keeper-etc-confd-files
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "clickhouseOperator.labels" . | nindent 4 }}
data:
  readme: Templates in this folder are packaged with an operator and available via 'useTemplate'
